#! /usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/busy]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-01 19:55:12 UTC
# Updated     : 2026-09-15 15:08:44 UTC
# Description : Look busy when the boss comes around.
# -----------------------------------------------------------------------------

busy() {
    # (ref) <https://www.commandlinefu.com/commands/view/6663/pretend-to-be-busy-in-office-to-enjoy-a-cup-of-coffee>
    # Ctrl+C to quit.

    # --( AEL-BASHLIB )--------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications

    check_applications bash cat grep hexdump || return 1

    # ---( MAIN )--------------------------------------------------------------

    command cat /dev/urandom \
    | command hexdump -C \
    | command grep --color=always 'ca fe'
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    busy
fi
