#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/deep-nmap]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2026-04-03 15:53:06 UTC
# Updated     : 2026-09-15 15:24:53 UTC
# Description : Deep Nmap scan.
# -----------------------------------------------------------------------------

deep-nmap() {

    # --( AEL-BASHLIB )--------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications messages

    check_applications cat nmap sudo || return 1

    usage() {
        cat <<EOF
===============================================================================
[+] deep-nmap - Deep Nmap scan.
===============================================================================
Usage:
  deep-nmap <Target> [Nmap Options] | [-h|--help]

Runs Nmap as sudo with customizable arguments. Defaults to:
  -sV          - Detect service versions.
  -O           - Enable OS detection.
  -sC          - Run Nmap's default scripts.
  --traceroute - Perform a traceroute to the target.

Options:
  -h, --help    - Display this help message.

Examples:
  deep-nmap 192.168.1.1
  deep-nmap scanme.nmap.org --Pn
-------------------------------------------------------------------------------
EOF
    }

    # --- Arguments parsing ---------------------------------------------------

    # No args handle.
    [[ $# -eq 0 ]] && { usage; return 1; }

    # Handle help.
    for arg in "$@"; do
        case "${arg}" in
            -h|--help)
                usage
                return 1
                ;;
        esac
    done

    # --- Run deep-nmap -------------------------------------------------------

    message banner "Runing deep-nmap (sudo nmap -sV -O -sC --traceroute ${*})."
    if ! command -v grc >/dev/null; then
        sudo nmap -sV -O -sC --traceroute "$@"
    else
        sudo grc nmap -sV -O -sC --traceroute "$@"
    fi

    return 0
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    deep-nmap "$@"
fi
