#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/dicom-tag]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2021-07-14 09:38:38 UTC
# Updated     : 2026-09-28 18:34:59 UTC
# Description : Search DICOM tags.
# -----------------------------------------------------------------------------

# ---( AEL-BASHLIB )-----------------------------------------------------------

if [[ -z "${AEL_BASHLIB:-}" ]]; then
    printf '%s\n' \
        'Warning: $AEL_BASHLIB is not set.' \
        '' \
        'The recommended location is:' \
        '  ~/.local/share/ael/ael-bashlib' \
        '' \
        'Set it with:' \
        '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
        ''
fi

bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

if [[ ! -d "$bashlib_dir" ]]; then
    printf '%s\n' \
        'Error: AEL//BashLib is required but could not be found.' \
        '' \
        'Expected location:' \
        "  $bashlib_dir" \
        '' \
        'Installation instructions:' \
        '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
        '' >&2

    exit 1
fi

source ${AEL_BASHLIB}/ael
import applications messages

check_applications ael-fuzz || exit 1

if [[ ! -f "${AEL_DATA}/dicom-tags.json" ]]; then
    message error "Cannot find data file ${AEL_DATA}/dicom-tags.json."
fi    

ael-fuzz \
    --input json \
    --file "${AEL_DATA}/dicom-tags.json" \
    --value-field tag \
    --display-fields tag,keyword \
    --output display  
