#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/directory-size]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-01 20:01:01 UTC
# Updated     : 2026-09-28 18:35:56 UTC
# Description : Check size of biggest directories.
# -----------------------------------------------------------------------------

directory-size() {

    # ---( AEL-BASHLIB )-------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import messages

    message banner "[+] directory-size"
    message step "Size of current directory, followed by biggest child directories:"

    command du --bytes --human-readable --max-depth 1 2> /dev/null \
    | command sort --reverse --human-numeric-sort \
    | command head
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    directory-size
fi
