#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/elevate]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-02 00:10:38 UTC
# Updated     : 2026-09-28 18:36:27 UTC
# Description : Repeats last command with sudo, if forgotten.
# -----------------------------------------------------------------------------

elevate() {

    # ---( AEL-BASHLIB )-------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications messages

    check_applications bash sudo || return 1

    usage() {
        cat <<EOF
===============================================================================
[+] elevate - Repeats last command with sudo, if forgotten.
===============================================================================
Usage:
  elevate [--interactive][--help]

<elevate> runs sudo \$(history -p !!), which allows to run the last command 
with elevated privileges.

Options:
  -i, --interactive    Prompt for confirmation.
  -h, --help           Display this help message.

IMPORTANT:
  This script must be sourced, otherwise history won't act as intented.
-------------------------------------------------------------------------------
EOF
    }

    local __args=("${@}")
    local __arg

    # --- help ----------------------------------------------------------------
    for __arg in "${__args[@]}"; do
        if [ "${__arg}" == '-h' ] || [ "${__arg}" == '--help' ]; then
            usage
            return 0
        fi
    done

    # --- interactive ---------------------------------------------------------
    # ... Will exit in non-interactive context.
    
    local __input

    message banner "elevate - Repeats last command with sudo, if forgotten."
    for __arg in "${__args[@]}"; do
        if [[ "${__arg}" == '-i' ]] || [[ "${__arg}" == '--interactive' ]]; then
            if [[ ! -t 0 ]]; then
                message error "No interactive terminal available for confirmation prompt." >&2
                return 1
            fi
            message step "Are you sure you want to proceed? [y/N] "
            read -r __input
                if [[ "${__input}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                    sudo bash -c "$(history -p !!)"
                    return 0
                else
                    message error "Aborting running last command with elevated privileges."
                    return 1
                fi
        fi
    done

    sudo bash -c "$(history -p !!)"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    elevate --help
fi
