#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/emojis]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2022-06-02 08:56:47 UTC
# Updated     : 2026-09-28 18:37:16 UTC
# Description : Search emojis.
# -----------------------------------------------------------------------------

# ---( AEL-BASHLIB )-----------------------------------------------------------

if [[ -z "${AEL_BASHLIB:-}" ]]; then
    printf '%s\n' \
        'Warning: $AEL_BASHLIB is not set.' \
        '' \
        'The recommended location is:' \
        '  ~/.local/share/ael/ael-bashlib' \
        '' \
        'Set it with:' \
        '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
        ''
fi

bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

if [[ ! -d "$bashlib_dir" ]]; then
    printf '%s\n' \
        'Error: AEL//BashLib is required but could not be found.' \
        '' \
        'Expected location:' \
        "  $bashlib_dir" \
        '' \
        'Installation instructions:' \
        '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
        '' >&2

    exit 1
fi

source ${AEL_BASHLIB}/ael
import applications messages

check_applications ael-fuzz || exit 0

_DATA="${AEL_DATA}/emojis.json"

if [[ ! -f "$_DATA" ]]; then
    message error "Cannot find data file $_DATA"
    exit 1
fi    

_SELECTION=$(
    ael-fuzz \
        --input json \
        --file "$_DATA" \
        --value-field emoji \
        --display-fields emoji,name,codepoints
)

if [[ -z "${_SELECTION}" ]]; then
    exit 0
fi

if [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
    check_applications wl-copy || exit 0
    printf '%s' "$_SELECTION" | wl-copy
else
    check_applications xclip || exit 0
    printf '%s' "$_SELECTION" | xclip -selection clipboard
fi

message result "emojis - Selected emoji:"
printf '%s\n' "${_SELECTION}"
