#! /usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/pacman-reset]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-10-20 10:46:22 UTC
# Updated     : 2026-09-17 11:19:52 UTC
# Description : Re-initialize pacman sync, mirrorlist and keyring.
# -----------------------------------------------------------------------------

pacman-reset() {

    # ---( AEL-BASHLIB )-------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications messages
        
    check_applications reflector sudo pacman || return 1

    message banner "pacmn-reset - Re-initializing Pacman."

    message step "Removing sync file."
    sudo $(command -v rm) -rf /var/lib/pacman/sync

    # Resetting mirror list using `reflector` instead of curl.
    message step "Resetting mirrorlist."
    sudo reflector --country Canada --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

    message step "Updating archlinux-keyring."
    sudo $(command -v pacman) -Syy --noconfirm archlinux-keyring

    message success "All done!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    pacman-reset
fi
