#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/ports]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-04 02:11:08 UTC
# Updated     : 2026-09-21 11:24:26 UTC
# Description : Displays all listening and active TCP/UDP ports, including the processes associated with them.
# -----------------------------------------------------------------------------

ports() {

    # ---( AEL-BASHLIB )-------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications messages

    check_applications sudo netstat || return 1

    message banner "ports - Displays open ports"

    if [[ $(command -v grc) ]]; then
        sudo grc netstat -tulanp
    else
        sudo netstat -tulanp
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    ports
fi
