#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/ports]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-04 02:11:08 UTC
# Updated     : 2026-09-21 11:24:26 UTC
# Description : Displays all listening and active TCP/UDP ports, including the processes associated with them.
# -----------------------------------------------------------------------------

ports() {

    source ${HOME}/.ael/lib/bash/ael
    import applications messages

    check_applications sudo netstat || return 1

    message banner "ports - Displays open ports"

    if [[ $(command -v grc) ]]; then
        sudo grc netstat -tulanp
    else
        sudo netstat -tulanp
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    ports
fi
