#! /usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/py-cleaner]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-02 00:59:00 UTC
# Updated     : 2026-09-21 11:10:58 UTC
# Description : Cleans Python-generated cache files from the current directory and its subdirectories.
# -----------------------------------------------------------------------------

py-cleaner () {

    source ${HOME}/.ael/lib/bash/ael
    import applications messages

    # --- (ref.) <https://stackoverflow.com/a/41386937/10500496>
 
    check_applications find || return 1

    message banner "py-cleaner - Cleaning python current directory."

    command find . \( -type f -name '*.py[co]' -o -type d -name __pycache__ \) -delete

    message success "Current directory cleaned."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    py-cleaner
fi
