#! /usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/py-cleaner]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2023-08-02 00:59:00 UTC
# Updated     : 2026-09-21 11:10:58 UTC
# Description : Cleans Python-generated cache files from the current directory and its subdirectories.
# -----------------------------------------------------------------------------

py-cleaner () {

    # ---( AEL-BASHLIB )-------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications messages

    # --- (ref.) <https://stackoverflow.com/a/41386937/10500496>
 
    check_applications find || return 1

    message banner "py-cleaner - Cleaning python current directory."

    command find . \( -type f -name '*.py[co]' -o -type d -name __pycache__ \) -delete

    message success "Current directory cleaned."
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    py-cleaner
fi
