#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/virtual-boxes]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2025-02-18 20:57:09 UTC
# Updated     : 2026-09-28 18:03:46 UTC
# Description : Virtualbox VMs launcher.
# -----------------------------------------------------------------------------

set -o pipefail

# ---( AEL-BASHLIB )----------------------------------------------------------|

if [[ -z "${AEL_BASHLIB:-}" ]]; then
    printf '%s\n' \
        'Warning: $AEL_BASHLIB is not set.' \
        '' \
        'The recommended location is:' \
        '  ~/.local/share/ael/ael-bashlib' \
        '' \
        'Set it with:' \
        '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
        ''
fi

bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

if [[ ! -d "$bashlib_dir" ]]; then
    printf '%s\n' \
        'Error: AEL//BashLib is required but could not be found.' \
        '' \
        'Expected location:' \
        "  $bashlib_dir" \
        '' \
        'Installation instructions:' \
        '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
        '' >&2

    exit 1
fi

source ${AEL_BASHLIB}/ael
import applications messages

check_applications awk jq VBoxManage ael-fuzz || exit 1

# ===( List to json )==========================================================

_vm_uuid=$(
    VBoxManage list vms |
        awk -F'"' '
            {
                name=$2
                uuid=$3

                gsub(/^[[:space:]]*\{/, "", uuid)
                gsub(/\}[[:space:]]*$/, "", uuid)

                printf "%s\t%s\n", name, uuid
            }
        ' |
        jq -R -s '
            split("\n")
            | map(select(length > 0))
            | map(
                split("\t")
                | {
                    _vm_name: .[0],
                    _vm_uuid: .[1]
                }
            )
        '
)

# ===( SELECTION )=============================================================

_SELECTION=$(printf '%s\n' "${_vm_uuid}" | ael-fuzz \
                                  --frontend quickshell \
                                  --input json \
                                  --value-field _vm_uuid \
                                  --display-fields _vm_name
)

[[ -z "$_SELECTION" ]] && exit 0

message success "Starting VM: $_SELECTION"
VBoxManage startvm "$_SELECTION"
