#!/usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/ael-bin/whoisweb]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2026-04-07 10:33:23 UTC
# Updated     : 2026-09-18 11:29:32 UTC
# Description : Query WHOIS web if <whois> port 43 is blocked on your network.
# -----------------------------------------------------------------------------

whoisweb() {

    # ---( AEL-BASHLIB )-------------------------------------------------------
    
    if [[ -z "${AEL_BASHLIB:-}" ]]; then
        printf '%s\n' \
            'Warning: $AEL_BASHLIB is not set.' \
            '' \
            'The recommended location is:' \
            '  ~/.local/share/ael/ael-bashlib' \
            '' \
            'Set it with:' \
            '  export AEL_BASHLIB="$HOME/.local/share/ael/ael-bashlib"' \
            ''
    fi

    bashlib_dir="${AEL_BASHLIB:-$HOME/.local/share/ael/ael-bashlib}"

    if [[ ! -d "$bashlib_dir" ]]; then
        printf '%s\n' \
            'Error: AEL//BashLib is required but could not be found.' \
            '' \
            'Expected location:' \
            "  $bashlib_dir" \
            '' \
            'Installation instructions:' \
            '  https://github.com/alterEGO-Linux/ael-documentation/components/ael-bashlib/INDEX.md' \
            '' >&2

        exit 1
    fi

    source ${AEL_BASHLIB}/ael
    import applications
    import messages

    check_applications curl jq sed || return 1

    message banner "whoiweb - Web WHOIS"

    if [[ -z "${@}" ]]; then
        message error "You must provide a valid URL."
    else
        command curl --silent https://whoisjs.com/api/v1/${1} \
        | command jq ".raw" \
        | command sed "s/\\\r\\\n/\\n/g"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    whoisweb "$@"
fi
